### ISSUE TITLE
XCIPTV API

### ISSUE THREAD

**Issue by kevwhite** [gtaman92/XtreamCodesExtendAPI#7]
@gtaman92 the ottrun company have released an API now as well for xciptv app - Would this be able to be implemented into your script? https://github.com/davewood2013/XtreamCodes16API/

**Comment by kevwhite** [comment]
Implemented it seperately myself - If you need it give me a shout

**Comment by brasmeat** [comment]
i need this api can you send me?
marioverdini@hotmail.com

**Comment by n0ky4** [comment]
Conseguiu mano?

**Comment by stephen18jones** [comment]
On the basis of my experience, the IPTV Smarters Pro is a really great app ever. UI is very modern & responsive. Using it for over 8 months already and no crashes, even not any single problem. An amazing feature like RecordingsFeature, Parental control, multi DNS Support, EPG support, and many more.
SIMPLY IPTV SMARTERS PRO IS THE BEST IPTV APP IN THE APP STORE FOR IPTV STREAMING
